### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by cseanburns** [trashboi-rtx/ICT-420#1]
Some things to fix:

- remove all CSS, including the top `<style>` section and in-line CSS styles
- on line 29 you have `<section class: "Header" style = "text-align:center">`. It should only be `<section>`. Same thing with similar lines.
- on line 45 you have `<a/>`. It should be `</a>`
- the `align` attribute is obsolete, and need to use CSS to style anyway
- there shouldn't be any spaces between attribute name and value in this kind of syntax: `<a href = "Resume.pdf">`. It should be `<a href="Resume.pdf">`. 

After fixing those, check your HTML here: https://html5.validator.nu/ And then fix any other errors that are found.

**Comment by trashboi-rtx** [comment]
Fixed
